name: Compile

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta

      - name: Install Dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run lint:prettier

      - name: Run test
        run: npm test
