name: Check schema diff

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate schema
        run: npx typescript-json-schema ./src/config.ts Config -o config-schema.json

      - name: Check diff
        run: git diff --exit-code config-schema.json
